task:
  name: FreeBSD $FREEBSD_VERSION (Python $PYTHON_VERSION)

  freebsd_instance:
    cpu: 1
    image_family: $FREEBSD_IMAGE

  matrix:
    - env:
        FREEBSD_VERSION: 12.1
        FREEBSD_IMAGE: freebsd-12-1
    - env:
        FREEBSD_VERSION: 12.1 STABLE
        FREEBSD_IMAGE: freebsd-12-1-snap
    # - env:
    #     FREEBSD_VERSION: 13.0
    #     FREEBSD_IMAGE: freebsd-13-0-snap

  matrix:
    - env:
        PYTHON_VERSION: 3.8
        PYTHON_PORT_NAME: python38
    - env:
        PYTHON_VERSION: 3.7
        PYTHON_PORT_NAME: python37

  install_script:
    - pkg install -y curl
    - pkg install -y $PYTHON_PORT_NAME
    - pipenv install --dev
  lint_script:
    - pipenv run ./scripts/check.sh
  format_script:
    - pipenv run ./scripts/format.sh
    - test -z "$(git status --porcelain=v1)"
  test_script:
    - pipenv run pytest
