task:
  name: FreeBSD $FREEBSD_VERSION (Python $PYTHON_VERSION)

  freebsd_instance:
    cpu: 1
    image_family: $FREEBSD_IMAGE

  matrix:
    - env:
        FREEBSD_VERSION: 12.1
        FREEBSD_IMAGE: freebsd-12-1
    - env:
        FREEBSD_VERSION: 12.1 STABLE
        FREEBSD_IMAGE: freebsd-12-1-snap
    # - env:
    #     FREEBSD_VERSION: 13.0
    #     FREEBSD_IMAGE: freebsd-13-0-snap

  matrix:
    - env:
        PYTHON_VERSION: 3.8
        PYTHON_PORT_NAME: python38
        PYTHON_EXE: python3.8
        PIP_EXE: python3.8 -m pip
    - env:
        PYTHON_VERSION: 3.7
        PYTHON_PORT_NAME: python37
        PIP_PORT_NAME: py37-pip
        PYTHON_EXE: python3.7
        PIP_EXE: pip-3.7

  install_script:
    - pkg install -y $PYTHON_PORT_NAME
    - |
      set -e
      if [ -n "$PIP_PORT_NAME" ]; then
        pkg install -y "$PIP_PORT_NAME"
      else
        pkg install -y curl
        curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
        $PYTHON_EXE /tmp/get-pip.py install
        $PIP_EXE install -U pip
      fi
    - $PIP_EXE install pipenv
    - pipenv install --dev --deploy

  lint_script:
    - pipenv run ./scripts/check.sh
  format_script:
    - pipenv run ./scripts/format.sh
    - test -z "$(git status --porcelain=v1)"
  test_script:
    - pipenv run pytest
